name: Dispatch Events

on:
  release:
    types: [published]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch to ESPresense.com
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.ESPRESENSE_CONTENTS_TOKEN }}
          repository: ESPresense/ESPresense.com
          event-type: new-release
          client-payload: >
            {
              "repository": "ESPresense/ESPresense-companion",
              "ref": "${{ github.ref }}",
              "sha": "${{ github.sha }}"
            }

      - name: Repository Dispatch to hass-addons
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.ESPRESENSE_CONTENTS_TOKEN }}
          repository: ESPresense/hass-addons
          event-type: update-version
          client-payload: >
            {
              "repository": "ESPresense/ESPresense-companion",
              "ref": "${{ github.ref }}",
              "sha": "${{ github.sha }}"
            }
